version: '3'
services:
  sse-mongodb:
    image: mongo:4.1.2
    hostname: mongodb
    command: mongod
    ports:
    - 27017:27017
  sse-pgdb:
    image: postgres:9.4
    ports:
    - 5432:5432
    volumes:
    - sse-vol:/var/lib/postgresql/sample
    environment:
    - POSTGRES_USER=sse
    - POSTGRES_PASSWORD=sse
volumes:
  sse-vol: